from pathlib import Path

mydir = "s3://pawsey1132.atol.testassembly"


rule createFile:
    output:
        outfile=storage.s3(
            Path(mydir, "testfile.snakemake.txt").as_posix(),
        ),
    container:
        "docker://amazon/aws-cli:2.22.31"
    resources:
        runtime=1,
        mem_mb=1000,
    threads: 1
    shell:
        """
        echo 'Written by snakemake' > {output.outfile}
        uname -n >> {output.outfile}
        date >> {output.outfile}
        """
