from pathlib import Path

mydir = storage.s3("s3://pawsey1132.atol.testassembly")


rule createFile:
    output:
        outfile=Path(mydir, "testfile.snakemake.txt"),
    container:
        "docker://amazon/aws-cli:2.22.31"
    resources:
        runtime=1,
        mem_mb=1000,
    threads: 1
    shell:
        """
        echo 'Written by snakemake' > {output.outfile}
        uname -n >> {output.outfile}
        date >> {output.outfile}
        """
